### PR TITLE
Handle GKE Connect Gateway URL differences

### LINKED ISSUE #245: Please add support for gkeMemberships in Connect Gateway endpoint URL
### TL;DR

Some recent clusters and/or Connect Gateway API seem to be using a slightly different format for their endpoint:
```
 https://connectgateway.googleapis.com/v1/projects/<PROJECT_NUMBER>/locations/<LOCATION>/gkeMemberships/<MEMBERSHIP_NAME>
```
(note `gkeMemberships` here instead of just `memberships`).

Connections using the older format don't seem to work, and I'd like to add support for that.

### Detailed design

My proposed design for backwards compatibility is to just allow both formats with a non-capturing group in the `membershipResourceNamePattern` [regex](https://github.com/google-github-actions/get-gke-credentials/blob/6aa34f068185d76c47cd024a47d97fca2baa5b52/src/gkeClient.ts#L35):
```ts
/^projects\/(.+)\/locations\/(.+)\/(?:memberships|gkeMemberships)\/(.+)$/i,
```

Alternatively, if the new format is the new "default" for the Connect Gateway API, we should adjust the action to use only that instead of `memberships` (but I'm curious to hear your thoughts, since I don't have an inside view).

The current regex makes it impossible to override the new endpoints using `fleet_membership_name`. And when the old format is used, the connection just hangs for a little and then returns `the server doesn't have a resource type <X>` for any request when using this Action.

I've tested this locally with the same Workload Identity Service Account, and only the endpoint with `gkeMemberships` works:
```
$ curl -sH "Authorization: Bearer $(gcloud auth print-access-token)" https://connectgateway.googleapis.com/v1/projects/<PROJECT_NUMBER>/locations/global/gkeMemberships/<MEMBERSHIP>/api/v1/namespaces/default
{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","uid":"<uuid>","resourceVersion":"204","creationTimestamp":"<timestamp>","labels":{"kubernetes.io/metadata.name":"default"},"managedFields":[{"manager":"kube-apiserver","operation":"Update","apiVersion":"v1","time":"<time>","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:kubernetes.io/metadata.name":{}}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}

$ curl -sH "Authorization: Bearer $(gcloud auth print-access-token)" https://connectgateway.googleapis.com/v1/projects/<PROJECT_NUMBER>/locations/global/memberships/<MEMBERSHIP>/api/v1/namespaces/default
[{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
]
```

When using `gcloud container fleet memberships get-credentials` locally, it also stores the URL in the new format (which is how I was able to discover it) - e.g.
```
$  k config view | head -4
apiVersion: v1
clusters:
- cluster:
    server: https://connectgateway.googleapis.com/v1/projects/<PROJECT_NUMBER>/locations/global/memberships/<MEMBERSHIP>
```

Curiously, the fleet membership API also returns the URL is the old format, so I'm not sure how `gcloud` is able to infer `gkeMemberships` from that (but assuming there's some business logic for that):
```
$ gcloud container fleet memberships describe <MEMBERSHIP> --format 'value(name)'
projects/<PROJECT_ID>/locations/global/memberships/<MEMBERSHIP>
```

### Additional information

I've only found reference to `gkeMemberships` in a very recent [Google Cloud blog post](https://cloud.google.com/blog/products/containers-kubernetes/connect-gateway-with-argocd), so I'm assuming this change is quite new, but it seems to be breaking. It appears not to a public API yet, hence such changes are expected, but the Action needs to be adjusted as well.

### LINKED ISSUE #253: google-github-actions/get-gke-credentials failed with: not found: projects/***/zones/us-central1-a/clusters/autopilot-cluster-1.
### TL;DR

get-gke-credentials are failing with below error message,

google-github-actions/get-gke-credentials failed with: not found: projects/***/zones/us-central1-a/clusters/autopilot-cluster-1.

github action link: https://github.com/avisatna/ProductAPI/actions/runs/3505258773/jobs/5871453330

### Expected behavior

_No response_

### Observed behavior

_No response_

### Action YAML

```yaml
github action link: https://github.com/avisatna/ProductAPI/actions/runs/3505258773/jobs/5871453330
```

### Log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sethvargo**
This PR changes the Connect Gateway builder to always lookup the given membership and determine if the resulting cluster is a GKE cluster. If it is a GKE cluster, it uses the /gkeMemberships collection endpoint. Otherwise, it uses the standard /memberships collection endpiont.

It also drops the e2e test in favor of just using kubectl directly.

- Closes #256
- Closes #245
- Closes #253
- Gets us closer to supporting #257

### CODE REVIEW

File: src/gkeClient.ts [hunk 1]
```diff
@@ -270,16 +277,17 @@ export class ClusterClient {
...
       url: url,
       headers: {
         'User-Agent': userAgent,
       },
-    })) as HubMembershipsListResponse;
+    })) as HubMembershipsResponse;
 
     const memberships = resp.data.resources;
-    if (memberships.length < 1) {
+    if (!memberships || memberships.length < 1) {
```
Comment (sethvargo) [inline src/gkeClient.ts:290]: This was a bug I found in testing. Sometimes the response comes back as null instead of `[]`, which then NPEd on `.length`.

File: src/gkeClient.ts [hunk 2]
```diff
@@ -226,38 +226,45 @@ export class ClusterClient {
...
-    return `${this.connectGatewayHostPath}/projects/${projectNum}/locations/${membershipRef.location}/memberships/${membershipRef.membershipName}`;
-  }
-
-  /**
-   * Retrieves a Cluster.
-   *
-   * @param fqn Cluster name
-   * @returns a Cluster object.
-   */
-  async getCluster(clusterName: string): Promise<ClusterResponse> {
```
Comment (sethvargo) [inline src/gkeClient.ts:247]: This moved below to keep the Connect Gateway code colocated.

File: src/gkeClient.ts [hunk 3]
```diff
@@ -226,38 +226,45 @@ export class ClusterClient {
...
-    const url = `${this.defaultEndpoint}/${this.getResource(clusterName)}`;
+  async getConnectGWEndpoint(name: string): Promise<string> {
+    const membershipURL = `${this.hubEndpoint}/${name}`;
     const resp = (await this.auth.request({
-      url: url,
+      url: membershipURL,
       headers: {
         'User-Agent': userAgent,
       },
```
Comment (bharathkkb) [inline src/gkeClient.ts:241]: Since we do a lookup, it might be good to call out any new permissions needed like `gkehub.memberships.get` in the connect gateway readme section.

File: README.md [hunk 4]
```diff
@@ -82,15 +82,14 @@ jobs:
...
+-   `use_connect_gateway` - (Optional) If true, uses the [Connect Gateway
+    endpoint](https://cloud.google.com/anthos/multicluster-management/gateway)
+    to connect to the cluster. The default value is false.
 
 -   `fleet_membership_name` - (Optional) Fleet membership name of form
-      "projects/PROJECT_ID/locations/LOCATION/memberships/MEMBERSHIP_NAME"
-      to use for generating Connect Gateway endpoint.
-      This only applies if "use_connect_gateway" is true.
-      Defaults to auto discovery if empty.
+    "projects/PROJECT_ID/locations/LOCATION/memberships/MEMBERSHIP_NAME" to use
```
Comment (verbanicm) [inline README.md:90]: Should this also be updated to reflect the gkeMemberships pattern as well?

File: src/gkeClient.ts [hunk 5]
```diff
@@ -414,17 +442,24 @@ export type ClusterResponse = {
 /**
  * HubMembershipsListResponse is the response from listing GKE Hub memberships.
```
Comment (bharathkkb) [inline src/gkeClient.ts:443]:
```suggestion
 * HubMembershipsResponse is the response from listing GKE Hub memberships.
```

File: src/gkeClient.ts [hunk 6]
```diff
@@ -226,38 +226,45 @@ export class ClusterClient {
   }
 
   /**
-   * Constructs a Connect Gateway endpoint string of form
-   * connectGatewayEndpoint/v1/projects/123/locations/l/memberships/m
+   * Constructs a Connect Gateway endpoint string from the given fleet
+   * membership name.
    *
-   * @param membershipName membership name.
+   * @param name membership name in the format projects/p/locations/l/memberships/m
```
Comment (verbanicm) [inline src/gkeClient.ts:232]: Same here (gkeMemberships) for consistency sake?

**Review by verbanicm — APPROVED** [review]

File: src/gkeClient.ts [hunk 7]
```diff
@@ -112,7 +112,7 @@ export class ClusterClient {
     const matches = name.match(membershipResourceNamePattern);
     if (!matches) {
       throw new Error(
-        `Failed to parse membership name "${name}": invalid pattern. Should be of form projects/PROJECT_ID/locations/LOCATION/memberships/MEMBERSHIP_NAME`,
+        `Failed to parse membership name "${name}": invalid pattern. Should be of form projects/PROJECT_ID/locations/LOCATION/gkeMemberships/MEMBERSHIP_NAME or projects/PROJECT_ID/locations/LOCATION/memberships/MEMBERSHIP_NAME`,
```
Comment (bharathkkb) [inline src/gkeClient.ts:115]: Per b/261052807, wouldn't memberships.Get always return in format `projects/p/locations/l/memberships/m`? My understanding was only the connect gateway URL supports multiple collection types.

**Review by bharathkkb — COMMENTED** [review]
LGTM, a few questions

File: src/gkeClient.ts (hunk 7 above)
Comment (sethvargo) [reply src/gkeClient.ts:115]: Theoretically yes, but I want to handle the case where someone copy-pastes from their kubeconfig, since this is extremely nuanced.

**Review by bharathkkb — APPROVED** [review]
